name: build
on:
    push:
        branches:
            - main
        tags:
            - 'v*'
jobs:
    build:
        runs-on: ubuntu-latest^
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '12.x'
            always-auth: true
            registry-url: 'https://registry.npmjs.org'
        - name: Install dependencies
          run: npm ci
        - name: Execute tests
          run: npm run test-ci:lib
        - name: Build library
          run: npm run build-ci:lib
        - name: Copy README
          run: cp README.md dist/packages/environment/README.md
        - name: Publish library
          if: startsWith(github.ref, 'refs/tags/')
          run: npm publish --access public
          working-directory: dist/packages/environment
